In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df=pd.read_csv("heart.csv")
df

age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
0     63    1   3     145   233    1  ...     0      2.3    0    0      1       1
1     37    1   2     130   250    0  ...     0      3.5    0    0      2       1
2     41    0   1     130   204    0  ...     0      1.4    2    0      2       1
3     56    1   1     120   236    0  ...     0      0.8    2    0      2       1
4     57    0   0     120   354    0  ...     1      0.6    2    0      2       1
..   ...  ...  ..     ...   ...  ...  ...   ...      ...  ...  ...    ...     ...
298   57    0   0     140   241    0  ...     1      0.2    1    0      3       0
299   45    1   3     110   264    0  ...     0      1.2    1    0      3       0
300   68    1   0     144   193    1  ...     0      3.4    1    2      3       0
301   57    1   0     130   131    0  ...     1      1.2    1    1      3       0
302   57    0   1     130   236    0  ...     0      0.0    1    1      2       0

[303 rows x 14 columns]

***Data Ananlysis***

In [ ]:
df.head()

age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
0   63    1   3     145   233    1  ...     0      2.3    0    0      1       1
1   37    1   2     130   250    0  ...     0      3.5    0    0      2       1
2   41    0   1     130   204    0  ...     0      1.4    2    0      2       1
3   56    1   1     120   236    0  ...     0      0.8    2    0      2       1
4   57    0   0     120   354    0  ...     1      0.6    2    0      2       1

[5 rows x 14 columns]

In [ ]:
df.tail()

age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
298   57    0   0     140   241    0  ...     1      0.2    1    0      3       0
299   45    1   3     110   264    0  ...     0      1.2    1    0      3       0
300   68    1   0     144   193    1  ...     0      3.4    1    2      3       0
301   57    1   0     130   131    0  ...     1      1.2    1    1      3       0
302   57    0   1     130   236    0  ...     0      0.0    1    1      2       0

[5 rows x 14 columns]

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

Since we dont have any null values there is no need of Data Filling in Preprocessing

***Removal of Given Features***

In [ ]:
dropcols=['oldpeak','slp','thall']
df=df.drop(dropcols,axis=1)

In [ ]:
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  caa  output
0     63    1   3     145   233    1        0       150     0    0       1
1     37    1   2     130   250    0        1       187     0    0       1
2     41    0   1     130   204    0        0       172     0    0       1
3     56    1   1     120   236    0        1       178     0    0       1
4     57    0   0     120   354    0        1       163     1    0       1
..   ...  ...  ..     ...   ...  ...      ...       ...   ...  ...     ...
298   57    0   0     140   241    0        1       123     1    0       0
299   45    1   3     110   264    0        1       132     0    0       0
300   68    1   0     144   193    1        1       141     0    2       0
301   57    1   0     130   131    0        1       115     1    1       0
302   57    0   1     130   236    0        0       174     0    1       0

[303 rows x 11 columns]

***Differentiating Input from Output***

In [ ]:
Y=df[['output']]

In [ ]:
X=df.drop(Y,axis=1)

In [ ]:
Y

output
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [ ]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2)

In [ ]:
Xtrain

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  caa
144   76    0   2     140   197    0        2       116     0    0
221   55    1   0     140   217    0        1       111     1    0
270   46    1   0     120   249    0        0       144     0    0
247   66    1   1     160   246    0        1       120     1    3
84    42    0   0     102   265    0        0       122     0    0
..   ...  ...  ..     ...   ...  ...      ...       ...   ...  ...
42    45    1   0     104   208    0        0       148     1    0
45    52    1   1     120   325    0        1       172     0    0
112   64    0   2     140   313    0        1       133     0    0
220   63    0   0     150   407    0        0       154     0    3
123   54    0   2     108   267    0        0       167     0    0

[242 rows x 10 columns]

***Models***

***Logistic Regression***

In [ ]:
reg=LogisticRegression()
reg.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
ypred=reg.predict(Xtest)
ypred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [ ]:
reg.score(Xtest,Ytest)

0.7868852459016393

***Decision Tree***

In [ ]:
regdc=DecisionTreeClassifier(criterion='gini')
regdc.fit(Xtrain,Ytrain)

DecisionTreeClassifier()

In [ ]:
regdc.predict(Xtest)

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1])

In [ ]:
regdc.score(Xtest,Ytest)

0.7377049180327869

***Random Forest***

In [ ]:
regrf=RandomForestClassifier(n_estimators=200)
regrf.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(n_estimators=200)

In [ ]:
regrf.predict(Xtest)

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
regrf.score(Xtest,Ytest)

0.819672131147541

***K Nearest Neighbour***

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
knn.predict(Xtest)

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [ ]:
knn.score(Xtest,Ytest)

0.639344262295082

***SVM***

In [ ]:
svm=svm.SVC(kernel='linear')
svm.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [ ]:
svm.predict(Xtest)

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [ ]:
svm.score(Xtest,Ytest)

0.7868852459016393