In [2]:
##Ques 1

In [3]:
%run ./AddNum.ipynb

A=int(input())
B=int(input())
Add(A,B)
Sub(A,B)

6
9
the addition is:15
the subtraction is:-3


In [4]:
##Ques 2

In [5]:
import os

APP_FOLDER = 'D:\Riot Games'

totalFiles = 0


for base, dirs, files in os.walk(APP_FOLDER):
    print('Searching in : ',base)
    for Files in files:
        totalFiles += 1
    


print('Total number of files',totalFiles)



Searching in :  D:\Riot Games
Searching in :  D:\Riot Games\Riot Client
Searching in :  D:\Riot Games\Riot Client\Resources
Searching in :  D:\Riot Games\Riot Client\UX
Searching in :  D:\Riot Games\Riot Client\UX\GPUCache
Searching in :  D:\Riot Games\Riot Client\UX\locales
Searching in :  D:\Riot Games\Riot Client\UX\Plugins
Searching in :  D:\Riot Games\Riot Client\UX\Plugins\rcp-fe-keystone-react
Searching in :  D:\Riot Games\Riot Client\UX\Plugins\rcp-fe-plugin-runner
Searching in :  D:\Riot Games\Riot Client\UX\swiftshader
Searching in :  D:\Riot Games\VALORANT
Searching in :  D:\Riot Games\VALORANT\live
Searching in :  D:\Riot Games\VALORANT\live\Engine
Searching in :  D:\Riot Games\VALORANT\live\Engine\Binaries
Searching in :  D:\Riot Games\VALORANT\live\Engine\Binaries\ThirdParty
Searching in :  D:\Riot Games\VALORANT\live\Engine\Binaries\ThirdParty\CEF3
Searching in :  D:\Riot Games\VALORANT\live\Engine\Binaries\ThirdParty\CEF3\Win64
Searching in :  D:\Riot Games\VALORANT\liv

In [10]:
##Ques 3

In [11]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
for i in range(8):
    for j in range(8):
        if ((i+j)%2!=0):
            x[i,j]=1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
##Ques 4

In [13]:
#taking two array inputs from user
array1=[]
array2=[]
commonelements=[]
print("enter 5 elements for each array")
for i in range(5):
    ele=int(input())
    array1.append(ele)
print(array1)
for i in range(5):
    ele=int(input())
    array2.append(ele)
print(array2)
for i in range(5):
    for j in range(5):
        if(array1[i]==array2[j]):
            commonelements.append(array1[i])
print(np.unique(commonelements))


enter 5 elements for each array
6
9
69
169
1169
[6, 9, 69, 169, 1169]
9
6
96
196
1196
[9, 6, 96, 196, 1196]
[6 9]


In [14]:
##Ques 5

In [15]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
